#!/usr/bin/env python3
"""Build a self-contained static report from the workspace's study runs.

Output: ``_pages/workspace/`` containing:

  index.html                                    workspace landing page
  studies/<slug>/index.html                     per-study page (viz iframes)
  studies/<slug>/viz/*.html                     copied from studies/<slug>/viz/

The viz HTML files are already self-contained (Plotly CDN + Three.js +
embedded JSON data), so the static site needs no server.

Designed to be published to gh-pages under ``/workspace/``. See
``scripts/publish-pages.sh`` for the deploy step.
"""
from __future__ import annotations

import html as html_lib
import shutil
from pathlib import Path

import yaml


HERE = Path(__file__).resolve().parent.parent
STUDIES = HERE / "studies"
OUT = HERE / "_pages" / "workspace"


CSS = """
<style>
  body { font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         color: #1f2937; background: #f9fafb; margin: 0;
         padding: 24px; max-width: 1200px; margin-left: auto; margin-right: auto; }
  h1 { font-size: 24px; margin: 0 0 8px 0; }
  h2 { font-size: 20px; margin: 28px 0 8px 0; }
  h3 { font-size: 16px; margin: 18px 0 6px 0; }
  p.muted { color: #6b7280; font-size: 13px; margin: 0 0 16px 0; }
  .card { background: #fff; border: 1px solid #e5e7eb; border-radius: 8px;
          padding: 14px 16px; margin-bottom: 12px; }
  .card a { color: #4338ca; text-decoration: none; font-weight: 600; }
  .card a:hover { text-decoration: underline; }
  .card-row { display: flex; justify-content: space-between;
              align-items: baseline; gap: 12px; }
  .meta { color: #6b7280; font-size: 12px; }
  .tag { display: inline-block; background: #eef2ff; color: #4338ca;
         padding: 1px 8px; border-radius: 10px; font-size: 11px; margin-right: 6px; }
  iframe { width: 100%; border: 1px solid #e5e7eb; border-radius: 6px;
           background: #fff; display: block; margin-bottom: 16px; }
  .viz-block { background: #fff; border: 1px solid #e5e7eb;
               border-radius: 8px; padding: 12px; margin-bottom: 14px; }
  .viz-title { font-weight: 600; margin-bottom: 8px; }
  .nav { font-size: 13px; margin-bottom: 16px; }
  .nav a { color: #4338ca; text-decoration: none; margin-right: 12px; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb;
            color: #9ca3af; font-size: 12px; }
</style>
"""


def _load_workspace() -> dict:
    return yaml.safe_load((HERE / "workspace.yaml").read_text())


def _load_study(slug: str) -> dict | None:
    p = STUDIES / slug / "study.yaml"
    if not p.is_file():
        return None
    return yaml.safe_load(p.read_text())


def _build_study_page(slug: str, viz_files: list[Path]) -> str:
    spec = _load_study(slug) or {}
    title = spec.get("name") or slug
    purpose = (spec.get("purpose") or {}).get("question", "")
    description = (spec.get("purpose") or {}).get("expected_outcome", "")
    declared_vizzes = spec.get("visualizations") or []
    declared_names = [v.get("name") for v in declared_vizzes]
    # Sort viz files to match the study's declaration order; trailing
    # entries (auto-discovered etc.) come last alphabetically.
    by_name = {f.stem: f for f in viz_files}
    ordered: list[Path] = []
    for name in declared_names:
        if name in by_name:
            ordered.append(by_name.pop(name))
    ordered.extend(sorted(by_name.values()))

    blocks = []
    for f in ordered:
        # Determine a reasonable iframe height based on the embedded
        # _autosize_script(N) declaration in the viz HTML.
        text = f.read_text()
        import re
        m = re.search(r"iframes\[i\]\.style\.height = '(\d+)px';", text)
        h = int(m.group(1)) if m else 500
        blocks.append(
            f'<div class="viz-block">'
            f'<div class="viz-title">{html_lib.escape(f.stem)}</div>'
            f'<iframe src="viz/{f.name}" style="height:{h}px"></iframe>'
            f'</div>'
        )

    return (
        f"<!doctype html><html><head><meta charset='utf-8'/>"
        f"<title>{html_lib.escape(title)} — workspace report</title>"
        f"{CSS}</head><body>"
        f"<div class='nav'><a href='../../'>← workspace</a></div>"
        f"<h1>{html_lib.escape(title)}</h1>"
        f"<p class='muted'>{html_lib.escape(purpose)}</p>"
        f"{('<p>'+html_lib.escape(description)+'</p>') if description else ''}"
        + "".join(blocks)
        + "<div class='footer'>Generated by scripts/build-static-report.py · "
        "viz HTML is self-contained (Plotly + Three.js) — no server required.</div>"
        "</body></html>"
    )


def _build_index(workspace: dict, study_summaries: list[dict]) -> str:
    name = workspace.get("name", "pbg-membrane-actin-composite")
    cards = []
    for s in study_summaries:
        tags = "".join(
            f"<span class='tag'>{html_lib.escape(t)}</span>"
            for t in (s.get("tags") or [])[:4]
        )
        cards.append(
            f"<div class='card'>"
            f"<div class='card-row'><a href='studies/{s['slug']}/'>{html_lib.escape(s['slug'])}</a>"
            f"<span class='meta'>{s['viz_count']} viz · {s['phase']}</span></div>"
            f"<p style='margin:6px 0 0 0;color:#374151'>{html_lib.escape(s['question'])}</p>"
            f"<div style='margin-top:6px'>{tags}</div>"
            f"</div>"
        )

    expert_docs = workspace.get("expert_docs") or []
    expert_lines = "".join(
        f"<li><strong>{html_lib.escape(d.get('name',''))}</strong> — "
        f"{html_lib.escape((d.get('description') or '').strip().split(chr(10))[0])}</li>"
        for d in expert_docs
    )

    return (
        f"<!doctype html><html><head><meta charset='utf-8'/>"
        f"<title>{html_lib.escape(name)} — workspace report</title>"
        f"{CSS}</head><body>"
        f"<h1>{html_lib.escape(name)}</h1>"
        f"<p class='muted'>Static workspace report. Each card below links to a "
        f"study page with its full viz panel (Plotly + Three.js).</p>"
        f"<h2>Studies</h2>"
        + "".join(cards)
        + (f"<h2>Expert docs</h2><ul>{expert_lines}</ul>" if expert_lines else "")
        + "<div class='footer'>Generated by scripts/build-static-report.py — "
        "the dashboard SPA at <code>reports/index.html</code> is the live "
        "counterpart (needs <code>vivarium-dashboard serve</code> to run).</div>"
        "</body></html>"
    )


def main() -> int:
    workspace = _load_workspace()
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    study_summaries: list[dict] = []
    for study_dir in sorted(STUDIES.iterdir()):
        if not study_dir.is_dir():
            continue
        slug = study_dir.name
        viz_dir = study_dir / "viz"
        if not viz_dir.is_dir():
            continue
        viz_files = sorted(viz_dir.glob("*.html"))
        if not viz_files:
            continue
        spec = _load_study(slug) or {}
        question = (spec.get("purpose") or {}).get("question", "")
        phase = spec.get("phase") or spec.get("status") or ""
        tags = ((spec.get("baseline") or [{}])[0].get("composite") or "").split(".")[-1:]

        # Copy viz files
        out_study = OUT / "studies" / slug
        out_study_viz = out_study / "viz"
        out_study_viz.mkdir(parents=True)
        for f in viz_files:
            shutil.copy2(f, out_study_viz / f.name)

        # Build per-study page
        (out_study / "index.html").write_text(_build_study_page(slug, viz_files))

        study_summaries.append({
            "slug": slug,
            "question": question,
            "phase": phase,
            "tags": tags,
            "viz_count": len(viz_files),
        })

    (OUT / "index.html").write_text(_build_index(workspace, study_summaries))

    print(f"built {OUT.relative_to(HERE)}/")
    print(f"  studies: {len(study_summaries)}")
    print(f"  viz files: {sum(s['viz_count'] for s in study_summaries)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
